# Generated by Django 2.2.5 on 2020-03-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_auto_20200326_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='CQI_AVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='CQI_att_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='CQI_upto6_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='CQI_upto6_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='Cell_usage_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='Connection_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_congestion_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_connect_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_connect_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_connect_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_drop_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_release_anomalous_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='ERAB_release_att_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='LTE_GSM_redirect_blind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='LTE_GSM_redirect_noblind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='LTE_UTRAN_redirect_blind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='LTE_UTRAN_redirect_noblind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='Out_of_service_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='PRB_att_num_dl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='PRB_usage_num_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='PRB_utilization_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RLC_PDU_att_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RLC_PDU_retrans_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RLC_PDU_retrans_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_congestion_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_connect_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_connect_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_connect_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_connectuser_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_connectuser_num_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_license_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_reconnect_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_reconnect_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RRC_reconnect_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='RTWPperrb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='Running_att_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='Sensing_rate_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='Sensing_rate_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='TB_double_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='TB_double_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='TB_one_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='TTI_schedule_num_dl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='cell_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.Lte_site_info'),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_inter_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_inter_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_inter_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_intra_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_intra_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_intra_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_s1_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_x2_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='handover_x2_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='poor_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_busy',
            name='throughput',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='CQI_AVG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='CQI_att_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='CQI_upto6_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='CQI_upto6_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='Cell_usage_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='Connection_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_congestion_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_connect_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_connect_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_connect_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_drop_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_release_anomalous_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='ERAB_release_att_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='LTE_GSM_redirect_blind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='LTE_GSM_redirect_noblind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='LTE_UTRAN_redirect_blind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='LTE_UTRAN_redirect_noblind',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='Out_of_service_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='PRB_att_num_dl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='PRB_usage_num_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='PRB_utilization_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RLC_PDU_att_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RLC_PDU_retrans_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RLC_PDU_retrans_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_congestion_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_connect_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_connect_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_connect_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_connectuser_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_connectuser_num_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_license_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_reconnect_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_reconnect_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RRC_reconnect_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='RTWPperrb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='Running_att_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='Sensing_rate_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='Sensing_rate_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='TB_double_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='TB_double_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='TB_one_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='TTI_schedule_num_dl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='cell_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpi.Lte_site_info'),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_inter_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_inter_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_inter_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_intra_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_intra_req_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_intra_succ_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_s1_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_x2_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='handover_x2_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='poor_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_kpi_daily',
            name='throughput',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='cellname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='city',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='coveragetype',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='district',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='enbid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='equipmentvendors',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='groundclass1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='groundclass2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lte_site_info',
            name='praiseground',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
