# Generated by Django 2.2.5 on 2020-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_auto_20200326_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='groundclass1',
            new_name='antenna_type',
        ),
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='enbid',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='praiseground',
            new_name='buid_period',
        ),
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='latitude',
            new_name='celllatitude',
        ),
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='longitude',
            new_name='celllongitude',
        ),
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='coveragetype',
            new_name='grid_branch',
        ),
        migrations.RenameField(
            model_name='lte_site_info',
            old_name='equipmentvendors',
            new_name='grid_marketing',
        ),
        migrations.RemoveField(
            model_name='lte_site_info',
            name='groundclass2',
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='bandwidth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='co_2gcellid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='co_3grnccellid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='co_3grncnodeb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='common_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='commonmsg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='device_types',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='eci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='electrical_angle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='enblatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='enblongitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='enodebid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='enodebname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='freq_dl',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='freq_ul',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='grid_old',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='ground',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='howtogo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='mechanics_angle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='networking_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='onair_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='pci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='sectorid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='site_azimuth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='site_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='site_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='site_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='subnet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='tac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lte_site_info',
            name='tower_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
