# Generated by Django 2.2.5 on 2020-04-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_auto_20200407_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lte_site_info',
            name='common_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
